# Override CMake's FindBullet module:
# create an IMPORTED TARGET

include("${CMAKE_ROOT}/Modules/FindBullet.cmake")

if(BULLET_FOUND)
  list(GET BULLET_LIBRARIES 0 BULLET_FIRST_LIBRARY)
  set(BULLET_OTHER_LIBRARIES "${BULLET_LIBRARIES}")
  list(REMOVE_AT BULLET_OTHER_LIBRARIES 0)
  add_library(bullet::bullet UNKNOWN IMPORTED)
  set_target_properties(bullet::bullet PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
    IMPORTED_LOCATION "${BULLET_FIRST_LIBRARY}"
    INTERFACE_LINK_LIBRARIES "${BULLET_OTHER_LIBRARIES}"
    INTERFACE_INCLUDE_DIRECTORIES "${BULLET_INCLUDE_DIR}"
    )
endif()
